import type { RepositoryReportAxis } from "../shared/repositoryReport";
import type { Locale } from "./locale";

const ko = {
  meta: { title: "MyAiScore — 공개 저장소의 AI 협업 신호", description: "로그인 없이 공개 GitHub 저장소의 맥락, 검증 체계, 기록·추적, 자동화 신호를 확인해 보세요." },
  language: { label: "언어 선택", ko: "한국어", en: "EN" },
  shell: {
    skip: "본문으로 건너뛰기", brandHome: "MyAiScore 홈", beta: "데모", navLabel: "주요 메뉴",
    home: "홈", profile: "내 리포트", insights: "해석 가이드", evaluate: "저장소 분석", github: "GitHub", sponsorSite: "MyAiScore 후원하기", footerLinksLabel: "저장소·후원 링크",
    footerLead: "공개 저장소에 남은 자료로 AI 활용 습관을 살펴봅니다.", footerLimit: "개인의 역량이나 프로젝트 전체의 품질을 평가하지 않아요.",
  },
  report: {
    aria: "저장소 분석 리포트", demoTag: "가상 예시", demoDescription: "화면 구성을 보여주려고 만든 가상 데이터예요. 실제 분석 결과가 아니에요.",
    styleEyebrow: "저장소에서 확인된 협업 특성", repository: "저장소", commit: "커밋",
    boundaryStrong: "이 결과는 저장소에 남은 신호일 뿐, 개인의 AI 실력을 인증하지 않아요.", boundaryMore: "실제 대화에서 어떤 판단을 했는지, 결과물이 얼마나 좋은지까지는 알 수 없어요.",
    axesEyebrow: "네 가지 저장소 신호", axesHeading: "어떤 신호가 점수에 반영됐나요?", candidateUnknown: "후보 파일 수 미확인",
    candidate: (count: number) => `후보 파일 ${count}개`, selected: (count: number) => `분석 파일 ${count}개`, read: (count: number) => `${count}개 확인 완료`,
    complete: "수집 완료", partial: "일부 수집", staticOnly: "저장소에 남아 있는 정적 신호만 반영",
    evidenceFiles: (count: number) => `근거 파일 ${count}개`, noSignal: "분석한 파일에서는 이 축과 관련된 신호를 확인하지 못했습니다.",
    gapsEyebrow: "미확인 신호", gapsHeading: "확인하지 못한 신호도 함께 보여드려요.", noGaps: "이번 규칙에서 따로 표시된 빈칸은 없어요.",
    coverageDetails: "분석 범위와 기준 보기", treeTruncated: "GitHub가 파일 트리를 일부만 반환했어요.", selectionLimited: "후보 파일이 많아서 정해진 한도만큼만 골라 읽었어요.",
    nextChallenge: "다음 단계", recommendations: "추천 개선 과제", recommendationsIntro: "예상 작업량과 점수 개선 폭을 함께 보고, 효과가 큰 작업부터 추천해요.", saveIntro: "저장은 선택이에요. 원문이나 GitHub 계정 정보 없이 이 요약만 지금 쓰는 브라우저에 저장돼요.",
    save: "이 브라우저에 저장", downloadCard: "결과 카드 저장", shareCard: "결과 카드 공유", cardIntro: "결과 카드는 저장소명·커밋·점수·유형만 담으며 원문은 포함하지 않아요.", insightsLink: "점수 해석 보기 →", saved: "이 브라우저의 ‘내 리포트’에 저장했어요.", saveError: "브라우저 저장 공간에 리포트를 저장하지 못했어요.", cardSaved: "PNG 결과 카드를 저장했어요.", cardShared: "결과 카드를 공유했어요.", cardShareFallback: "이 브라우저는 이미지 공유를 지원하지 않아 PNG로 저장했어요.", cardError: "결과 카드를 만들지 못했어요. 잠시 뒤 다시 시도해 주세요.",
  },
  home: {
    kicker: "로그인 없이 바로 시작", title1: "AI로 코딩하고 있는데,", title2: "제대로 활용하고 있을까요?", lead1: "GitHub 공개 저장소 주소 하나만 입력하면", lead2: "맥락·검증·기록·자동화와 관련된 신호를 확인할 수 있습니다.",
    primary: "내 저장소 분석하기 ↗", example: "예시 리포트 보기 ↘", availability: "회원가입 불필요 · 공개 저장소만 분석 · AI 모델 호출 없음",
    demoTag: "예시 화면", demoCaption: "개인 역량이 아닌, 저장소에 남은 AI 활용 신호를 반영한 예시입니다.",
    chapters: [{ label: "분석 방법", text: "주소 하나로 바로 확인합니다." }, { label: "확인 범위", text: "저장소에 남은 신호만 분석합니다." }, { label: "리포트 예시", text: "점수와 근거를 함께 보여드립니다." }],
    flowLabel: "01 / 분석 방법", flowSide: "공개 GitHub 저장소", flowTitle1: "복잡한 설정 없이,", flowTitle2: "저장소 링크 하나면 충분해요.", flowIntro: "GitHub 로그인이나 별도 설치 없이 공개 저장소 주소만 입력하면 돼요.",
    steps: [{ title: "저장소 주소 입력", text: "분석할 공개 GitHub 저장소 주소를 붙여 넣어요." }, { title: "네 가지 기준 확인", text: "문서, 테스트, 커밋 기록, 자동화 설정을 살펴봐요." }, { title: "점수와 근거 확인", text: "점수에 반영된 파일과 부족한 부분, 다음에 개선할 항목까지 함께 보여드려요." }],
    scopeLabel: "02 / 확인 범위", scopeSide: "볼 수 있는 것만 점수에 반영해요", scopeTitle1: "저장소에 남은 자료만,", scopeTitle2: "확인한 만큼 보여드려요.", scopeLead1: "알 수 있는 것과", scopeLead2: "알 수 없는 것을 나눠서 보여드려요.", scopeKnownLabel: "확인할 수 있어요", scopeBody1: "프로젝트 문서, 테스트, CI, 커밋 기록, 자동화 설정", scopeUnknownLabel: "확인할 수 없어요", scopeBody2: "AI와 나눈 실제 대화, 제안을 받아들이거나 거절한 이유, 개인의 기여도", scopeClosing: "그래서 이 점수는 개인의 AI 실력 평가가 아니라, 저장소에 드러난 AI 활용 습관을 살펴보는 참고 자료예요.",
    demoLabel: "03 / 리포트 예시", demoSide: "가상 데이터", demoTitle1: "점수보다 중요한 건", demoTitle2: "그 뒤에 남은 근거입니다.", demoIntro1: "아래 리포트는 화면을 보여드리기 위한 가상 예시예요.", demoIntro2: "실제 저장소를 분석한 결과가 아닙니다.",
    profileCardLabel: "내 리포트", profileCardTitle: "원하는 결과만 이 브라우저에 저장해요.", profileCardText: "선택한 리포트를 현재 브라우저에 최대 20개까지 보관해요. 다른 기기와는 동기화되지 않아요.", insightsCardLabel: "해석 가이드", insightsCardTitle: "네 가지 점수가 무엇을 뜻하는지 확인해 보세요.", insightsCardText: "각 점수에 반영되는 항목과 해석할 때의 한계를 함께 설명해요.",
    closingKicker: "내 저장소 확인하기", closingTitle1: "저장소 링크를 넣고,", closingTitle2: "AI 활용 리포트를 확인해 보세요.", closingCta: "저장소 분석하기 ↗", closingText: "공개 GitHub 저장소 주소 하나면 돼요. 로그인은 필요하지 않아요.",
  },
  evaluate: {
    title: "공개 저장소 분석", description: "GitHub 주소 하나로 저장소에 남은 AI 협업 신호를 확인합니다.", label: "공개 GitHub 저장소 URL", placeholder: "https://github.com/owner/repository", submit: "저장소 분석하기", submitting: "분석 중…", help: "공개 저장소만 분석할 수 있습니다. GitHub 로그인이나 별도 계정은 필요하지 않습니다.",
    progressTitle: "저장소의 협업 신호를 찾고 있습니다.", progressText: "파일 목록을 고르고 맥락·검증·기록·자동화 신호를 확인합니다.", complete: "분석이 완료되었습니다.", genericError: "서버 응답을 확인할 수 없습니다. 잠시 후 다시 시도해 주세요.",
    cliSummary: "Claude Code 세션 리포트 CLI가 필요하다면", cliText: "선택한 로컬 Claude Code 세션의 활동 구성은 기존 CLI에서 별도로 만들 수 있습니다. 브라우저가 로컬 대화 기록을 자동으로 읽지는 않습니다.", cliCaption: "이 기능은 공개 저장소 분석과 다른 리포트이며, 설치된 MyAiScore 체크아웃과 Node.js가 필요합니다.",
    errors: {
      invalid_url: "공개 GitHub 저장소 주소 형식을 확인해 주세요.", unsupported_host: "공개 GitHub 저장소 주소 형식을 확인해 주세요.", invalid_commit_ref: "공개 GitHub 저장소 주소 형식을 확인해 주세요.",
      repo_not_found_or_private: "공개 저장소를 찾을 수 없어요. 비공개 저장소는 분석하지 않아요.", github_api_rate_limited: "GitHub 요청 한도에 도달했어요. 잠시 뒤 다시 시도해 주세요.", repository_report_rate_limited: "요청이 잠시 많아요. 잠시 뒤 다시 시도해 주세요.", repository_report_busy: "다른 저장소를 읽고 있어요. 잠시 뒤 다시 시도해 주세요.", repository_collection_failed: "공개 저장소를 읽지 못했어요. 잠시 뒤 다시 시도해 주세요.", repository_report_failed: "저장소 리포트를 만들지 못했어요. 잠시 뒤 다시 시도해 주세요.",
    },
  },
  profile: {
    title: "내 리포트", description: "직접 저장한 공개 저장소 분석 결과입니다.", newReport: "새 저장소 분석 →", privacy: "계정 없이 현재 브라우저에만 저장됩니다. 브라우저 데이터를 지우면 함께 삭제됩니다.", historyError: "저장된 리포트를 읽을 수 없습니다. 목록을 비우고 다시 시작해 주세요.", updateError: "브라우저 저장 공간을 업데이트하지 못했습니다.", emptyTitle: "저장한 리포트가 없습니다.", emptyText: "공개 저장소를 분석한 뒤 ‘이 브라우저에 저장’을 선택하면 여기에 표시됩니다.", emptyCta: "저장소 분석하기 →", historyAria: "저장된 저장소 리포트", files: (read: number, selected: number) => `${read}/${selected}개 파일`, view: "리포트 보기 →", remove: "삭제", clear: "저장된 리포트 모두 삭제", footnote: "같은 저장소와 커밋은 한 번만 저장되며 최근 결과를 최대 20개까지 보관합니다.", points: (value: number) => `${value}점`,
  },
  insights: {
    title: "해석 가이드", description: "네 가지 점수 축의 산정 기준과 해석 범위를 안내합니다.", savedReport: "리포트 선택", choose: "저장된 리포트 선택", emptyTitle: "선택한 리포트가 없습니다", emptyText: "저장소를 먼저 분석하거나, 위 목록에서 저장해 둔 리포트를 선택해 주세요.", emptyCta: "저장소 분석하기 →", guideEyebrow: "점수 읽는 법", guideTitle: "각 축은 최대 25점이에요.", range: "0–25점", guideText: "총점은 저장소에서 어떤 신호가 보였는지를 나타내요. 점수가 높다고 결과물이 더 좋거나 AI를 더 잘 쓴다는 뜻은 아니에요.",
    matrixEyebrow: "점수 산출 기준", matrixTitle: "신호별 배점과 산정 원칙을 공개합니다", matrixPrinciples: [{ label: "배점 방식", text: "각 신호의 기본 배점을 한 번만 적용하고, 내용의 실질과 저장소 내 범위를 함께 반영합니다." }, { label: "점수 상한", text: "네 가지 축은 각각 최대 25점이며, 총점은 최대 100점입니다." }, { label: "결과 일관성", text: "동일한 커밋과 규칙 버전, 동일한 수집 범위에서는 같은 결과가 계산됩니다." }], matrixCaption: "맥락·검증 기반·기록·자동화 네 축의 신호별 배점", matrixScrollLabel: "네 축의 신호별 배점표", matrixToggle: "접기/펼치기", axisHeader: "축", signalHeader: "저장소 신호", pointsHeader: "점수", axisTotal: "축 합계", points: (value: number) => `${value}점`,
    profileNamesEyebrow: "SJTI 16가지 유형 이름", profileNamesTitle: "SJTI 네 글자 코드는 어떤 이름으로 보이나요?", profileNamesIntro: "SJTI(Sang-Jun Type Indicator)는 D/R, H/P, S/T, F/E 네 차원의 조합으로 저장소 신호 유형에 16가지 이름을 붙입니다.",
    profileLimit: "축 기반 결과 스타일과 SJTI 유형은 저장소에 남은 신호를 요약한 라벨이며, 개인의 능력이나 성격을 평가하지 않습니다.",
    stylesEyebrow: "축 기반 결과 스타일", stylesTitle: "결과 이름은 네 축의 분포로 정해져요.", stylesIntro: "검증 수호자처럼 결과 카드에 표시되는 이름입니다. 아래 규칙을 위에서부터 확인해 처음 맞는 하나로 정해요.", ruleStep: (value: string) => `규칙 ${value}`, firstSignalsRule: (threshold: number) => `총점이 ${threshold}점보다 낮으면 이 스타일이에요.`, balancedRule: (minimum: number, spread: number) => `네 축이 모두 ${minimum}점 이상이고, 가장 높은 축과 가장 낮은 축의 차이가 ${spread}점 이하면 이 스타일이에요.`, dominantRule: (axis: string) => `${axis} 축이 가장 높으면 이 스타일이에요.`, tiePriority: (axes: string) => `가장 높은 축이 여러 개면 이 순서로 정해요 — ${axes}`, activeStyle: "현재 리포트 스타일", distributionNote: "이 리포트의 스타일도 총점이 아니라 네 축의 분포로 정해졌어요.",
  },
  presentation: {
    scoreLabel: "AI 개발 체계 점수", scoreExplanation: "선택된 공개 저장소에서 확인한 맥락·검증·기록·자동화 신호를 종합한 참고용 점수입니다. 개인의 AI 활용 능력이나 코드 품질, 실제 실행 결과를 평가하는 점수는 아닙니다.",
    axes: { context: { label: "맥락", question: "AI가 프로젝트의 목표와 규칙을 파악할 단서가 있나요?" }, verification: { label: "검증 기반", question: "결과를 확인할 테스트와 점검 장치가 있나요?" }, traceability: { label: "기록", question: "나중에 결정과 변경 이유를 따라갈 수 있나요?" }, automation: { label: "자동화", question: "반복 점검을 자동으로 돌릴 구조가 있나요?" } } satisfies Record<RepositoryReportAxis, { label: string; question: string }>,
  },
} as const;

type DeepWiden<T> = T extends (...args: infer A) => string ? (...args: A) => string : T extends string ? string : T extends readonly (infer U)[] ? readonly DeepWiden<U>[] : T extends object ? { [K in keyof T]: DeepWiden<T[K]> } : T;
export type Messages = DeepWiden<typeof ko>;

const en: Messages = {
  meta: { title: "MyAiScore — AI collaboration signals in public repositories", description: "Explore context, verification, traceability, and automation signals in a public GitHub repository without signing in." },
  language: { label: "Choose language", ko: "한국어", en: "EN" },
  shell: { skip: "Skip to content", brandHome: "MyAiScore home", beta: "DEMO", navLabel: "Main navigation", home: "Home", profile: "Reports", insights: "Guide", evaluate: "Analyze", github: "GitHub", sponsorSite: "Sponsor MyAiScore", footerLinksLabel: "Repository and sponsor links", footerLead: "Explore traces of AI collaboration in a public repository.", footerLimit: "Not a certification of personal AI ability." },
  report: {
    aria: "Repository analysis report", demoTag: "SYNTHETIC EXAMPLE", demoDescription: "Invented data that demonstrates the report layout. This is not a real repository result.", styleEyebrow: "Collaboration style visible in this repository", repository: "Repository", commit: "Commit",
    boundaryStrong: "This result describes signals left in a repository; it does not certify personal AI ability.", boundaryMore: "It cannot establish the decisions made in real conversations or the quality of the whole project.",
    axesEyebrow: "Four repository signals", axesHeading: "Which traces contributed to the score?", candidateUnknown: "Candidate count unavailable", candidate: count => `${count} candidates`, selected: count => `${count} selected`, read: count => `${count} read`, complete: "Collection complete", partial: "Partial collection", staticOnly: "Based only on static file signals",
    evidenceFiles: count => `${count} evidence ${count === 1 ? "file" : "files"}`, noSignal: "No signal for this axis was found in the selected sample.", gapsEyebrow: "What could not be established", gapsHeading: "Unknowns belong in the result.", noGaps: "No additional gap was identified by this rule.", coverageDetails: "Collection scope", treeTruncated: "GitHub returned only part of the repository tree.", selectionLimited: "The repository had more candidates than the bounded sample could read.", nextChallenge: "Next challenge", recommendations: "Highest-impact next steps", recommendationsIntro: "Priorities combine simulated score gain with fixed effort bands. Internal ranking coefficients are not shown.", saveIntro: "Saving is optional. Only this summary is stored in this browser, without source content or GitHub account data.", save: "Save in this browser", downloadCard: "Download result card", shareCard: "Share result card", cardIntro: "The card includes only the repository name, commit, score, and profile—never source content.", insightsLink: "Read the score guide →", saved: "Saved to My reports in this browser.", saveError: "The report could not be saved in browser storage.", cardSaved: "Downloaded the PNG result card.", cardShared: "Shared the result card.", cardShareFallback: "Image sharing is unavailable in this browser, so the PNG was downloaded instead.", cardError: "The result card could not be created. Please try again.",
  },
  home: {
    kicker: "Start without signing in", title1: "Find AI collaboration traces", title2: "in a public repository.", lead1: "Paste one public GitHub repository URL", lead2: "to inspect context, verification, records, and automation signals.", primary: "Analyze my repository ↗", example: "View an example report ↘", availability: "No account · Public repositories only · No AI model call", demoTag: "SYNTHETIC PREVIEW", demoCaption: "An example of repository signals, not a personal evaluation.",
    chapters: [{ label: "How it works", text: "Paste a URL. Inspect signals." }, { label: "What it sees", text: "Only traces left in files." }, { label: "The report", text: "Evidence and gaps together." }],
    flowLabel: "01 / HOW IT WORKS", flowSide: "PUBLIC GITHUB REPOSITORY", flowTitle1: "One URL is", flowTitle2: "enough to begin.", flowIntro: "Paste a public repository URL without GitHub login or CLI setup.", steps: [{ title: "Paste the URL.", text: "Use a public repository address in the form github.com/owner/repository." }, { title: "Find four kinds of signals.", text: "We inspect files and settings related to context, verification, traceability, and automation." }, { title: "Review evidence and gaps.", text: "The report shows file paths that contributed and what the repository could not establish." }],
    scopeLabel: "02 / SCOPE", scopeSide: "ONLY VISIBLE EVIDENCE COUNTS", scopeTitle1: "Only what remains", scopeTitle2: "in the repository.", scopeLead1: "We separate what is visible", scopeLead2: "from what remains unknown.", scopeKnownLabel: "What we can see", scopeBody1: "Project documentation, tests, CI, commit records, and automation settings", scopeUnknownLabel: "What we cannot see", scopeBody2: "Private AI conversations, reasons for accepting or rejecting suggestions, and individual contribution", scopeClosing: "This score is a reference for AI-use habits visible in the repository, not a rating of personal ability.",
    demoLabel: "03 / EXAMPLE REPORT", demoSide: "SYNTHETIC DATA", demoTitle1: "Start with the evidence,", demoTitle2: "then read the score.", demoIntro1: "The report below uses invented data to demonstrate the interface.", demoIntro2: "It is not the result of analyzing a real repository.", profileCardLabel: "MY REPORTS", profileCardTitle: "Keep only the results you choose.", profileCardText: "Store up to 20 reports in this browser.", insightsCardLabel: "GUIDE", insightsCardTitle: "Understand the four axes.", insightsCardText: "See what the score can and cannot say.", closingKicker: "START WITH A PUBLIC REPOSITORY", closingTitle1: "Paste a URL and", closingTitle2: "meet its collaboration signals.", closingCta: "Analyze a repository ↗", closingText: "No account. Only signals from a public repository.",
  },
  evaluate: {
    title: "Analyze a public repository", description: "Use one GitHub URL to inspect the AI collaboration signals left in its files.", label: "Public GitHub repository URL", placeholder: "https://github.com/owner/repository", submit: "Analyze repository", submitting: "Analyzing…", help: "Only public repositories are supported. No GitHub login or MyAiScore account is required.", progressTitle: "Looking for collaboration signals.", progressText: "Selecting files and checking context, verification, records, and automation traces.", complete: "Analysis complete.", genericError: "The server response could not be validated. Please try again shortly.", cliSummary: "Need the Claude Code session report CLI?", cliText: "The existing CLI can separately summarize activity in a selected local Claude Code session. The browser cannot automatically read local conversation records.", cliCaption: "This is separate from repository analysis and requires Node.js plus an installed MyAiScore checkout.",
    errors: { invalid_url: "Check the public GitHub repository URL format.", unsupported_host: "Check the public GitHub repository URL format.", invalid_commit_ref: "Check the public GitHub repository URL format.", repo_not_found_or_private: "The public repository could not be found. Private repositories are not supported.", github_api_rate_limited: "The GitHub request limit was reached. Please try again later.", repository_report_rate_limited: "There are too many requests right now. Please try again shortly.", repository_report_busy: "Another repository is being read. Please try again shortly.", repository_collection_failed: "The public repository could not be read. Please try again shortly.", repository_report_failed: "The repository report could not be created. Please try again shortly." },
  },
  profile: { title: "My reports", description: "Public repository reports you chose to save.", newReport: "Analyze another repository →", privacy: "Reports are stored only in this browser, without an account. Clearing browser data removes them.", historyError: "Saved reports could not be read. Clear the list to start again.", updateError: "Browser storage could not be updated.", emptyTitle: "No saved reports yet.", emptyText: "Analyze a public repository, then choose Save in this browser to keep the result here.", emptyCta: "Analyze a repository →", historyAria: "Saved repository reports", files: (read, selected) => `${read}/${selected} files`, view: "View report →", remove: "Remove", clear: "Clear saved reports", footnote: "The same repository and commit are stored once. This browser keeps up to 20 recent reports.", points: value => `${value} points` },
  insights: {
    title: "Guide", description: "Review how the four score axes are calculated and how to interpret their scope.", savedReport: "Choose report", choose: "Choose a saved report", emptyTitle: "No report selected", emptyText: "Analyze a repository first or choose a saved report from the list above.", emptyCta: "Analyze a repository →", guideEyebrow: "HOW TO READ THE SCORE", guideTitle: "Each axis contributes up to 25 points.", range: "0–25 points", guideText: "The total describes the mix of signals visible in the repository. A higher score does not prove better work or stronger personal AI ability.",
    matrixEyebrow: "SCORING CRITERIA", matrixTitle: "Signal points and scoring principles", matrixPrinciples: [{ label: "Point model", text: "Each signal receives its base points once, with content substance and repository breadth also reflected." }, { label: "Score cap", text: "Each of the four axes is capped at 25 points, for a maximum total of 100." }, { label: "Consistency", text: "The same commit, rule version, and collection scope produce the same result." }], matrixCaption: "Deterministic repository-signal points across four axes", matrixScrollLabel: "Point table for signals across four axes", matrixToggle: "Collapse or expand", axisHeader: "Axis", signalHeader: "Repository signal", pointsHeader: "Points", axisTotal: "Axis total", points: value => `${value} points`,
    profileNamesEyebrow: "SJTI PROFILE NAMES", profileNamesTitle: "How do SJTI four-letter codes read?", profileNamesIntro: "SJTI (Sang-Jun Type Indicator) combines D/R, H/P, S/T, and F/E into 16 repository-signal profile names.",
    profileLimit: "Axis-based result styles and SJTI profiles are labels summarizing signals left in the repository; they do not evaluate personal ability or personality.",
    stylesEyebrow: "AXIS-BASED RESULT STYLES", stylesTitle: "Result names come from the four-axis distribution.", stylesIntro: "These are the names shown on result cards, such as Quality Guardian. The first matching rule below determines the style.", ruleStep: value => `Rule ${value}`, firstSignalsRule: threshold => `Use this style when the total is below ${threshold}.`, balancedRule: (minimum, spread) => `Otherwise, use this style when every axis is at least ${minimum} and the highest-to-lowest spread is ${spread} or less.`, dominantRule: axis => `If neither earlier rule matches, use this style when ${axis} is the highest axis.`, tiePriority: axes => `Highest-axis tie priority: ${axes}.`, activeStyle: "CURRENT REPORT STYLE", distributionNote: "The current style also comes from the four-axis distribution, not a total-score band.",
  },
  presentation: { scoreLabel: "Repository AI collaboration readiness", scoreExplanation: "A playful sum of collaboration-readiness signals found in selected public repository files. It does not evaluate personal AI ability, code quality, or successful execution.", axes: { context: { label: "Context", question: "Are there clues that help AI understand the project's goals and rules?" }, verification: { label: "Verification basis", question: "Are there tests or checks intended to examine the result?" }, traceability: { label: "Traceability", question: "Can later readers follow decisions and changes?" }, automation: { label: "Automation", question: "Is there a foundation for running repeated checks automatically?" } } },
};

const messages: Record<Locale, Messages> = { ko, en };
export function messagesFor(locale: Locale): Messages { return messages[locale]; }
